In [1]:
import numpy as np

In [2]:
def nonlin(x, deriv=False):  # Note: there is a typo on this line in the video
    if(deriv==True):
        return (x*(1-x))
    
    return 1/(1+np.exp(-x))  # Note: there is a typo on this line in the video


In [3]:
#input data
X = np.array([[0,0,1],  # Note: there is a typo on this line in the video
            [0,1,1],
            [1,0,1],
            [1,1,1]])

In [4]:
#output data
y = np.array([[0],
             [1],
             [1],
             [0]])

In [5]:
np.random.seed(1)

In [10]:
#synapses
syn0 = 2*np.random.random((3,4)) - 1  # 3x4 matrix of weights ((2 inputs + 1 bias) x 4 nodes in the hidden layer)
syn1 = 2*np.random.random((4,1)) - 1  # 4x1 matrix of weights. (4 nodes x 1 output) - no bias term in the hidden layer.

In [22]:
for j in range(60000):
    
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    error = y - l2
    
    # Backprop
    l2_delta = error*nonlin(l2, deriv =True)
    l1_delta = l2_delta.dot(syn1.T)*nonlin(l1, deriv =True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print(l2)

[[ 0.00113869]
 [ 0.99703162]
 [ 0.99646414]
 [ 0.00404035]]


In [26]:
syn1

array([[-11.9704016 ],
       [  6.15169909],
       [ -4.1727122 ],
       [ 12.31206086]])

In [11]:


#training step
# Python2 Note: In the follow command, you may improve 
#   performance by replacing 'range' with 'xrange'. 
for j in range(60000):  
    
    # Calculate forward through the network.
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # Back propagation of errors using the chain rule. 
    l2_error = y - l2
    if(j % 10000) == 0:   # Only print the error every 10000 steps, to save time and limit the amount of output. 
        print("Error: " + str(np.mean(np.abs(l2_error))))
        
    l2_delta = l2_error*nonlin(l2, deriv=True)
    
    l1_error = l2_delta.dot(syn1.T)
    
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    #update weights (no learning rate term)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print("Output after training")
print(l2)

Error: 0.498143063951
Error: 0.0107390362688
Error: 0.00740748848689
Error: 0.00598422665189
Error: 0.00514985091533
Error: 0.00458623577905
Output after training
[[ 0.00168937]
 [ 0.99576532]
 [ 0.99497452]
 [ 0.00574317]]
